language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
#    - os: linux
    - os: osx
      brew_packages: opencv@3
      env: PKG_CONFIG_PATH="/usr/local/opt/opencv@3/lib/pkgconfig"
    - os: osx
      brew_packages: opencv
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:orangain/opencv'
    packages:
      - libopencv-dev

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
