language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - dist: xenial
    - os: osx
      brew_packages: opencv@3
      env: PKG_CONFIG_PATH="/usr/local/opt/opencv@3/lib/pkgconfig"
    - os: osx
      brew_packages: opencv
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:timsc/opencv-3.4'
    packages:
      - libopencv-dev
      - opencv-data

notifications:
  email:
    on_success: change
    on_failure: change
